FROM resin/%%RESIN_MACHINE_NAME%%-buildpack-deps

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
        ruby bundler \
  && apt-get clean && rm -rf /var/lib/apt/lists/*


#switch on systemd init system in container
ENV INITSYSTEM on

WORKDIR /usr/src/app
COPY ./Gemfile /Gemfile
RUN bundle install

COPY . /
CMD ["bundle" "exec" "ruby", "app.rb"]
