FROM resin/%%RESIN_MACHINE_NAME%%-alpine-buildpack-deps

RUN apk update \
  && apk add \
    ruby \
    ruby-bundler \
    ruby-json

#switch on systemd init system in container
ENV INITSYSTEM on

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN bundle install

CMD ["bundle" "exec" "ruby", "app.rb"]
