FROM resin/%%RESIN_MACHINE_NAME%%-buildpack-deps

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
        ruby ruby-dev bundler \
  && apt-get clean && rm -rf /var/lib/apt/lists/*


#switch on systemd init system in container
ENV INITSYSTEM on

COPY . /usr/src/app
RUN bundle install

WORKDIR /usr/src/app
CMD bundle exec ruby app.rb
